### ISSUE TITLE
Adding option for exceptions that can be filtered out

### ISSUE THREAD

**Issue by ridingrails** [hayesgm/ravenex#4]
Hi,

I am looking to add an option similar to Airbrake's `ignore:` or sentry-elixir's `filter:`. I would like to get your approval to merge this or something similar.

**Comment by hayesgm** [comment]
Sure, sounds great. Thanks for the PR.

**Comment by ridingrails** [comment]
Let me know if the added fixes are ok, then I can use this version in our apps 👍

**Comment by hayesgm** [comment]
Sorry for the delay, looks great. Can you bump the version and add a changelog message?

**Comment by ridingrails** [comment]
Do we need to have the lock at version 3.1 here? https://github.com/hayesgm/ravenex/commit/623cbf60832605c338fa4171433026600c867294#diff-7234367b857fd47fe1b5d1bcfd7e05edR9

**Comment by hayesgm** [comment]
Is the locked package version wrong for you?

**Comment by ridingrails** [comment]
I solved my issue, I had hackney (used by httpoison) locked at 1.6.6. Set it to 1.6.5. I will close this issue 👍
